# Generated by Django 2.1.4 on 2018-12-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('adr_id_city', models.IntegerField()),
                ('adr_id_street', models.IntegerField()),
                ('adr_id_home', models.IntegerField()),
                ('adr_entrance', models.SmallIntegerField()),
                ('adr_floor', models.SmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('mac_adr', models.CharField(max_length=20, unique=True)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('userport_start', models.PositiveSmallIntegerField()),
                ('userport_end', models.PositiveSmallIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments_Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_port', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('equipments_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.Equipments')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('adr_id_city', models.IntegerField()),
                ('adr_id_street', models.IntegerField()),
                ('adr_id_home', models.IntegerField()),
                ('vlan', models.PositiveSmallIntegerField()),
                ('network', models.GenericIPAddressField(protocol='IPv4')),
                ('netmask', models.PositiveSmallIntegerField()),
                ('gateway', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='Port_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipments_port',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.Lan'),
        ),
        migrations.AddField(
            model_name='equipments_port',
            name='port_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.Port_State'),
        ),
        migrations.AddField(
            model_name='equipments_model',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.Equipments_Type'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='equipments_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.Equipments_Model'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='equipments_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.Equipments_State'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.Lan'),
        ),
    ]
