# Generated by Django 2.1.4 on 2018-12-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lan',
            name='adr_id_city',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='adr_id_street',
        ),
        migrations.AlterField(
            model_name='lan',
            name='adr_id_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.Address'),
        ),
    ]
