# Generated by Django 2.1.4 on 2018-12-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.Equipments')),
            ],
        ),
        migrations.RemoveField(
            model_name='lan',
            name='location',
        ),
        migrations.AddField(
            model_name='port',
            name='lan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.Lan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog_lan',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipments.Lan'),
        ),
        migrations.AddField(
            model_name='catalog_lan',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.Address'),
        ),
    ]
