# Generated by Django 2.1.4 on 2018-12-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20181222_1605'),
        ('equipments', '0003_auto_20181224_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='adr_id_city',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='adr_id_home',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='adr_id_street',
        ),
        migrations.AddField(
            model_name='equipments',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='location.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
