# Generated by Django 2.1.4 on 2018-12-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_remove_catalog_lan_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='name',
            field=models.CharField(choices=[('WN', 'Склад (новое)'), ('WU', 'Склад (б/у)'), ('WB', 'Склад (сломано)'), ('I', 'Установлено'), ('UR', 'В ремонте'), ('WO', 'Списано')], default='WN', max_length=2),
        ),
    ]
